[package]
name = "q-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "^0"
thiserror = "1.0"
miette = "5.3" 
